' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.#ctor(System.Drawing.Graphics,System.Drawing.Color,System.Drawing.Drawing2D.CompositingQuality,System.Drawing.Drawing2D.SmoothingMode)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawArc(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawBezier(System.Single,System.Single,System.Single,System.Single,System.Single,System.Single,System.Single,System.Single,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawCircle(System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawCircle(System.Int64,System.Int64,System.Int64,System.Drawing.Pen,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawClosedCurve(System.Drawing.PointF[],System.Single,System.Drawing.Drawing2D.FillMode,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawCurve(System.Drawing.Point[],System.Int32,System.Int32,System.Single,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawEllipse(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawImage(System.Drawing.Image,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Drawing.GraphicsUnit)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawImage(System.String,System.Int64,System.Int64)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawLine(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawPath(System.Drawing.Drawing2D.GraphicsPath,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawPie(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawPolygon(System.Drawing.PointF[],System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawRectangle(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawRectangle(System.Int64,System.Int64,System.Int64,System.Int64,System.Drawing.Pen)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawSquare(System.Int32,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification:="<Pending>", Scope:="member", Target:="~M:DrawClasses.DrawClasses.Draw.DrawString(System.Int32,System.Int32,System.String,System.Drawing.Font,System.Drawing.StringFormat)")>
